"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { Card } from "@/components/ui";
export default function AdmissionsPage() {
  const [name, setName] = useState(""); const [source, setSource] = useState("website"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/admissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ applicant_name: name, source }) }); const payload = await response.json() as { message?: string }; if (!response.ok) throw new Error(payload.message ?? "Application could not be submitted."); setName(""); setMessage("Thank you. Your application has been received."); } catch (error) { setMessage(error instanceof Error ? error.message : "Application could not be submitted."); } finally { setBusy(false); } }
  return <main className="paper-grid min-h-screen px-5 py-8 sm:px-8 sm:py-12"><div className="mx-auto max-w-4xl"><Link href="/" className="text-sm font-semibold text-text-secondary">← School Platform</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_.9fr]"><header><p className="text-xs font-bold uppercase tracking-[0.18em] text-text-secondary">Admissions</p><h1 className="font-display mt-3 text-4xl font-semibold sm:text-6xl">Begin the next chapter.</h1><p className="mt-5 max-w-lg text-lg leading-8 text-text-secondary">Tell us who is applying and our admissions team will follow up with the next step.</p></header><Card><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Applicant name<input required minLength={2} maxLength={160} value={name} onChange={e => setName(e.target.value)} className="mt-1 min-h-12 w-full rounded-lg border border-[var(--border)] bg-surface-0 px-3" /></label><label className="block text-sm font-semibold">How did you hear about us?<select value={source} onChange={e => setSource(e.target.value)} className="mt-1 min-h-12 w-full rounded-lg border border-[var(--border)] bg-surface-0 px-3"><option value="website">Website</option><option value="referral">Referral</option><option value="walk-in">Walk-in</option><option value="other">Other</option></select></label><button disabled={busy} className="min-h-12 w-full rounded-lg bg-accent px-5 font-semibold text-[var(--accent-contrast)] disabled:opacity-50">{busy ? "Sending…" : "Submit application"}</button>{message && <p role="status" className="rounded-lg border border-[var(--border)] bg-surface-2 p-3 text-sm">{message}</p>}</form></Card></div></div></main>;
}
