import Link from "next/link";
import { Card, SectionHeading } from "@/components/ui";
import { PublicSiteNav } from "@/components/public-site-nav";
export const revalidate = 3600;
export default function Home() {
  return <main className="min-h-screen px-5 pb-24 pt-6 sm:px-8 sm:py-10">
    <div className="mx-auto max-w-6xl"><PublicSiteNav />
      <section className="grid items-center gap-12 pb-16 pt-8 lg:grid-cols-[1.15fr_.85fr] lg:pb-24 lg:pt-16">
        <div><p className="eyebrow">A record of school life</p><h1 className="font-display mt-5 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-tight sm:text-7xl">Learning, community, and growth—kept together.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-text-secondary">A calm, low-data home for students, teachers, and the people who help a school move forward.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/admissions" className="inline-flex min-h-12 items-center justify-center rounded-[var(--radius-sm)] bg-accent px-5 font-semibold text-[var(--accent-contrast)] shadow-[0_10px_24px_color-mix(in_srgb,var(--accent)_28%,transparent)] hover:-translate-y-0.5 hover:bg-[var(--accent-light)]">Explore admissions <span aria-hidden="true">↗</span></Link><Link href="/about" className="inline-flex min-h-12 items-center justify-center rounded-[var(--radius-sm)] border border-[var(--border)] bg-surface-1 px-5 font-semibold hover:bg-surface-2">Learn about the school</Link></div></div>
        <Card className="relative overflow-hidden p-7 sm:p-9"><div className="absolute right-0 top-0 h-1 w-24 bg-accent" aria-hidden="true" /><p className="eyebrow">Built for the day-to-day</p><h2 className="font-display mt-4 text-3xl font-semibold">A clear start for every learner.</h2><p className="mt-5 leading-7 text-text-secondary">Find your place, keep track of your progress, and stay close to the school community without adding friction.</p><div className="mt-8 grid gap-3 border-t border-[var(--border)] pt-6 sm:grid-cols-3 lg:grid-cols-1"><div><p className="font-semibold">For students</p><p className="mt-1 text-sm text-text-secondary">Results, timetable, and profile in one view.</p></div><div><p className="font-semibold">For teachers</p><p className="mt-1 text-sm text-text-secondary">A focused home for classes and assessment.</p></div><div><p className="font-semibold">For the school</p><p className="mt-1 text-sm text-text-secondary">The signal needed to make good decisions.</p></div></div></Card>
      </section>
      <section className="border-t border-[var(--border)] py-12"><SectionHeading eyebrow="Start here" title="School, made easier to navigate." description="Everything has a place, and the important things stay close." /><div className="mt-8 grid gap-4 sm:grid-cols-3"><Link href="/about" className="group rounded-[var(--radius-md)] border border-[var(--border)] bg-surface-1 p-5 hover:-translate-y-0.5 hover:bg-surface-2"><p className="text-sm font-semibold">About the school</p><p className="mt-2 text-sm leading-6 text-text-secondary">Meet the values and people behind the work.</p><span className="mt-6 block text-sm font-semibold text-[var(--accent-light)]">Read more →</span></Link><Link href="/news" className="group rounded-[var(--radius-md)] border border-[var(--border)] bg-surface-1 p-5 hover:-translate-y-0.5 hover:bg-surface-2"><p className="text-sm font-semibold">Notes from campus</p><p className="mt-2 text-sm leading-6 text-text-secondary">Read the latest updates and school stories.</p><span className="mt-6 block text-sm font-semibold text-[var(--accent-light)]">Read news →</span></Link><Link href="/login" className="group rounded-[var(--radius-md)] border border-[var(--border)] bg-surface-1 p-5 hover:-translate-y-0.5 hover:bg-surface-2"><p className="text-sm font-semibold">Open the portal</p><p className="mt-2 text-sm leading-6 text-text-secondary">Sign in to your student, teacher, or admin space.</p><span className="mt-6 block text-sm font-semibold text-[var(--accent-light)]">Log in →</span></Link></div></section>
    </div>
  </main>;
}
