"use client";
import { useState } from "react";
import { Card } from "@/components/ui";
import { supabaseRequest } from "@/lib/supabase";
type ClassOption = { id: string; name: string };
type SubjectOption = { id: string; name: string; class_id: string };
export function SubjectManagement({ classes, subjects, schedules, onSubjectsChange, onStatus }: { classes: ClassOption[]; subjects: SubjectOption[]; schedules: { subject_id: string }[]; onSubjectsChange: (value: SubjectOption[]) => void; onStatus: (value: string) => void }) {
  const [classId, setClassId] = useState(""); const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [classOpen, setClassOpen] = useState(false);
  const visible = subjects.filter(item => item.class_id === classId && item.name.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => a.name.localeCompare(b.name));
  async function add() { const trimmed = name.trim(); if (!classId || !trimmed) return; try { const created = await supabaseRequest<SubjectOption[]>("Subject", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ name: trimmed, class_id: classId }) }); if (created?.[0]) onSubjectsChange([...subjects, created[0]]); setName(""); onStatus("Subject added to the selected class."); } catch (error) { onStatus(error instanceof Error ? error.message : "Subject could not be added."); } }
  async function remove(subject: SubjectOption) { if (schedules.some(item => item.subject_id === subject.id)) { onStatus("This subject is used by a schedule. Delete or edit that schedule first."); return; } if (!window.confirm(`Remove ${subject.name}?`)) return; try { await supabaseRequest(`Subject?id=eq.${encodeURIComponent(subject.id)}`, { method: "DELETE", headers: { Prefer: "return=minimal" } }); onSubjectsChange(subjects.filter(item => item.id !== subject.id)); onStatus("Subject removed."); } catch (error) { onStatus(error instanceof Error ? error.message : "Subject could not be removed."); } }
  return <Card className="p-4 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold sm:text-2xl">Subjects by class</h2><p className="mt-1 text-sm text-text-secondary">Add or remove subjects independently for each class.</p></div>{classId && <button type="button" onClick={() => { setClassId(""); setName(""); setQuery(""); }} className="min-h-11 shrink-0 text-sm font-semibold text-text-secondary">Collapse</button>}</div><div className="relative z-20 mt-5 max-w-sm"><button type="button" aria-expanded={classOpen} onClick={() => setClassOpen(value => !value)} className="min-h-10 w-full rounded-lg border border-[var(--border)] bg-surface-0 px-3 text-left text-sm sm:min-h-12">{classes.find(item => item.id === classId)?.name ?? "Select class"}</button>{classOpen && <div className="absolute left-0 right-0 top-full z-30 mt-1 max-h-56 overflow-y-auto rounded-lg border border-[var(--border)] bg-surface-0 shadow-[var(--shadow)]">{classes.map(item => <button type="button" key={item.id} onClick={() => { setClassId(item.id); setQuery(""); setClassOpen(false); }} className="block min-h-11 w-full px-3 text-left text-sm hover:bg-surface-2">{item.name}</button>)}</div>}</div>{classId && <><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New subject name" className="min-h-12 min-w-0 flex-1 rounded-lg border border-[var(--border)] bg-surface-0 px-3" /><button type="button" onClick={() => void add()} disabled={!name.trim()} className="min-h-12 rounded-lg bg-accent px-5 font-semibold text-[var(--accent-contrast)] disabled:opacity-40">Add subject</button></div><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subjects" className="mt-3 min-h-12 w-full rounded-lg border border-[var(--border)] bg-surface-0 px-3" /><div className="mt-3 divide-y divide-[var(--border)] border-t border-[var(--border)]">{visible.map(subject => <div key={subject.id} className="flex items-center justify-between gap-3 py-3"><span className="text-sm font-semibold">{subject.name}</span><button type="button" onClick={() => void remove(subject)} className="min-h-11 rounded-lg border border-[var(--danger)] px-3 text-sm font-semibold text-danger">Remove</button></div>)}{!visible.length && <p className="py-4 text-sm text-text-secondary">No matching subjects.</p>}</div></>}</Card>;
}
