"use client";
import { useState } from "react";
import { Card } from "@/components/ui";
import { supabaseRequest } from "@/lib/supabase";
type ClassOption = { id: string; name: string };
type SubjectOption = { id: string; name: string; class_id: string };
export function SubjectManagement({ classes, subjects, schedules, onSubjectsChange, onStatus }: { classes: ClassOption[]; subjects: SubjectOption[]; schedules: { subject_id: string }[]; onSubjectsChange: (value: SubjectOption[]) => void; onStatus: (value: string) => void }) {
  const [classId, setClassId] = useState(""); const [name, setName] = useState("");
  const visible = subjects.filter(item => item.class_id === classId).sort((a, b) => a.name.localeCompare(b.name));
  async function add() { const trimmed = name.trim(); if (!classId || !trimmed) return; try { const created = await supabaseRequest<SubjectOption[]>("Subject", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ name: trimmed, class_id: classId }) }); if (created?.[0]) onSubjectsChange([...subjects, created[0]]); setName(""); onStatus("Subject added to the selected class."); } catch (error) { onStatus(error instanceof Error ? error.message : "Subject could not be added."); } }
  async function remove(subject: SubjectOption) { if (schedules.some(item => item.subject_id === subject.id)) { onStatus("This subject is used by a schedule. Delete or edit that schedule first."); return; } if (!window.confirm(`Remove ${subject.name}?`)) return; try { await supabaseRequest(`Subject?id=eq.${encodeURIComponent(subject.id)}`, { method: "DELETE", headers: { Prefer: "return=minimal" } }); onSubjectsChange(subjects.filter(item => item.id !== subject.id)); onStatus("Subject removed."); } catch (error) { onStatus(error instanceof Error ? error.message : "Subject could not be removed."); } }
  return <Card className="p-4 sm:p-6"><h2 className="font-display text-xl font-semibold sm:text-2xl">Subjects by class</h2><p className="mt-1 text-sm text-text-secondary">Add or remove subjects independently for each class.</p><select value={classId} onChange={e => setClassId(e.target.value)} className="mt-5 min-h-12 w-full rounded-lg border border-[var(--border)] bg-surface-0 px-3"><option value="">Select class</option>{classes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{classId && <><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={name} onChange={e => setName(e.target.value)} placeholder="New subject name" className="min-h-12 min-w-0 flex-1 rounded-lg border border-[var(--border)] bg-surface-0 px-3" /><button type="button" onClick={() => void add()} disabled={!name.trim()} className="min-h-12 rounded-lg bg-accent px-5 font-semibold text-[var(--accent-contrast)] disabled:opacity-40">Add subject</button></div><div className="mt-5 divide-y divide-[var(--border)] border-t border-[var(--border)]">{visible.map(subject => <div key={subject.id} className="flex items-center justify-between gap-3 py-3"><span className="text-sm font-semibold">{subject.name}</span><button type="button" onClick={() => void remove(subject)} className="min-h-11 rounded-lg border border-[var(--danger)] px-3 text-sm font-semibold text-danger">Remove</button></div>)}{!visible.length && <p className="py-4 text-sm text-text-secondary">No subjects assigned to this class.</p>}</div></>}</Card>;
}
